# Generated by Django 5.1.6 on 2025-02-11 07:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_assistant', '0002_queryjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='legaldocument',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='queryjob',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='queryjob',
            index=models.Index(fields=['created_at'], name='legal_assis_created_a66d5a_idx'),
        ),
        migrations.AddIndex(
            model_name='queryjob',
            index=models.Index(fields=['status'], name='legal_assis_status_c428e6_idx'),
        ),
    ]
